{{- if .Values.gateway.create -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
  labels:
    app.kubernetes.io/name: {{ include "envoy-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
