apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-router.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "envoy-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "envoy-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
