{{- $gwPort := index .Values "envoy-router" "gateway" "port" | int }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy-router-test
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: envoy-proxy
            port:
              number: {{ $gwPort }}
