apiVersion: v2
name: envoy-router-test
description: Test chart — installs envoy-router and creates pp-* pods + internal ALB Ingress
type: application
version: 0.1.0

dependencies:
- name: envoy-router
  version: "0.1.0"
  repository: "file://../envoy-router"
